from pathlib import Path

# 1) Remove the upstream import-time network/debug probe so startup cannot
#    block on Invidious before the web server binds its port.
video_path = Path("/app/modified-tuberepair/tuberepair/api/video.py")
video_text = video_path.read_text()

probe = '''print(
    "TEST CHANNEL ID:",
    get_channel_id_from_name("MrBeast")
)

'''

if probe not in video_text:
    raise SystemExit("Expected upstream TEST CHANNEL ID block not found")

video_path.write_text(video_text.replace(probe, "", 1))
print("Removed upstream import-time TEST CHANNEL ID probe")

# 2) Keep Render's existing /healthz setting compatible with pure upstream.
#    This is infrastructure-only: it does not touch playback, feeds, login,
#    yt-dlp, ffmpeg, or any TubeRepair response used by the iPhone.
static_path = Path("/app/modified-tuberepair/tuberepair/api/static.py")
static_text = static_path.read_text()

if '@static.route("/healthz")' not in static_text:
    static_text += '''

@static.route("/healthz")
def render_healthz():
    return "ok", 200
'''
    static_path.write_text(static_text)

print("Ensured /healthz route exists for Render")


# 3) Fix stale/dead playback URLs shipped in upstream templates.
#    Several feeds advertise /video/sd/<id>, but upstream has no route for it.
#    The real playback endpoint is /getvideo/<id>.
templates_root = Path("/app/modified-tuberepair/tuberepair/templates")
patched_templates = []
for template in templates_root.rglob("*.jinja2"):
    text = template.read_text()
    if "/video/sd/" not in text:
        continue
    new_text = text.replace("/video/sd/", "/getvideo/")
    # Classic search's top-level content element claims 3GPP even though
    # getvideo() creates an MP4. Match the declared MIME to the real output.
    if template.as_posix().endswith("/classic/search.jinja2"):
        new_text = new_text.replace(
            '<content type="video/3gpp" src="{{url}}/getvideo/',
            '<content type="video/mp4" src="{{url}}/getvideo/'
        )
    template.write_text(new_text)
    patched_templates.append(str(template.relative_to(templates_root)))

print("Fixed dead /video/sd playback URLs in:", ", ".join(patched_templates))


# 4) Prevent stock YouTube from hanging forever on secondary Invidious
#    lookups. Upstream's get.fetch() has no timeout at all.
get_path = Path("/app/modified-tuberepair/tuberepair/modules/get.py")
get_text = get_path.read_text()
old_fetch = 'resp = session.get(url, headers={"User-Agent": "Mozilla/5.0","Accept": "application/json"},proxies=helpers.proxies)'
new_fetch = 'resp = session.get(url, headers={"User-Agent": "Mozilla/5.0","Accept": "application/json"}, proxies=helpers.proxies, timeout=8)'
if old_fetch not in get_text:
    raise SystemExit("Expected upstream get.fetch session.get anchor not found")
get_path.write_text(get_text.replace(old_fetch, new_fetch, 1))
print("Added 8-second timeout to upstream Invidious fetches")

# 5) Fix malformed author element in the single-video/batch feed.
batch_path = templates_root / "batch_videos.jinja2"
batch_text = batch_path.read_text()
if "<n>{{ video['author'] }}</n>" in batch_text:
    batch_text = batch_text.replace(
        "<n>{{ video['author'] }}</n>",
        "<name>{{ video['author'] }}</name>"
    )
    batch_path.write_text(batch_text)
print("Fixed batch/single-video author <name> tag")

# 6) Cache search entries and reuse them for the immediate single-video
#    request generated by the stock app after a row is tapped. This avoids
#    a redundant Invidious round-trip on the critical tap -> player path.
video_path = Path("/app/modified-tuberepair/tuberepair/api/video.py")
video_text = video_path.read_text()

cache_anchor = 'video = Blueprint("video", __name__)\n'
if '_recent_search_items = {}' not in video_text:
    if cache_anchor not in video_text:
        raise SystemExit("Video blueprint anchor not found")
    video_text = video_text.replace(
        cache_anchor,
        cache_anchor + '\n_recent_search_items = {}\n',
        1
    )

old_single = '''    data = get.fetch(f"{config.URL}/api/v1/videos/{video_id}")
    if not data:
        return get.error()

    item = normalize_video(data)
    if not item:
        return get.error()

    return get.template("batch_videos.jinja2", {
'''
new_single = '''    item = _recent_search_items.get(video_id)

    if item is not None:
        print("SINGLE VIDEO CACHE HIT:", video_id, flush=True)
    else:
        data = get.fetch(f"{config.URL}/api/v1/videos/{video_id}")
        if not data:
            return get.error()

        item = normalize_video(data)
        if not item:
            return get.error()

    return get.template("batch_videos.jinja2", {
'''
if old_single not in video_text:
    raise SystemExit("single_video_info block anchor not found")
video_text = video_text.replace(old_single, new_single, 1)

search_cache_anchor = '''            item["authorId"] = (
                item.get("authorId")
                if item.get("authorId") not in ["unknown", "Unknown", "", None]
                else get_channel_id_from_name(item.get("author"))
            )

            print(
                "UPLOADER DEBUG:",
'''
search_cache_replacement = '''            item["authorId"] = (
                item.get("authorId")
                if item.get("authorId") not in ["unknown", "Unknown", "", None]
                else get_channel_id_from_name(item.get("author"))
            )

            _recent_search_items[vid_id] = dict(item)

            print(
                "UPLOADER DEBUG:",
'''
if search_cache_anchor not in video_text:
    raise SystemExit("Search item cache anchor not found")
video_text = video_text.replace(search_cache_anchor, search_cache_replacement, 1)

video_path.write_text(video_text)
print("Enabled instant single-video cache for tapped search results")
